server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://118.25.213.214:3306/community?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: sfy1314
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true