server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://118.25.213.214:3306/community?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: sfy1314
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
sharing:
  security:
    jwt-key: XmchxCoder
    token-expired-in: 86400000